{
	"version": 1593718447,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"c2webappstart.js",
		"images/player1-sheet0.png",
		"images/player2-sheet0.png",
		"images/p2bullet-sheet0.png",
		"images/p1bullet-sheet0.png",
		"images/edgeofscreen.png",
		"images/p1thirdbullet-sheet0.png",
		"images/p2thirdbullet-sheet0.png",
		"images/p1lc1-sheet0.png",
		"images/p2rc1-sheet0.png",
		"images/p1lhc1-sheet0.png",
		"images/p2lhc1-sheet0.png",
		"images/p1rt1-sheet0.png",
		"images/p2rt1-sheet0.png",
		"images/p1bomb-sheet0.png",
		"images/p2bomb-sheet0.png",
		"images/fallplbar.png",
		"images/springplbar.png",
		"images/tiledbackground.png",
		"images/5972201grasstexture-sheet0.png",
		"images/spring-sheet0.png",
		"images/fall-sheet0.png",
		"images/rules-sheet0.png",
		"media/shanghai teahouse chinese tea - touhou kobuto v burst battle intro loop.m4a",
		"media/shanghai teahouse chinese tea - touhou kobuto v burst battle intro loop.ogg",
		"media/battle loop.ogg",
		"media/battle no loop.ogg",
		"media/spring victory.ogg",
		"media/fall victory.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}